#!/bin/bash
#--------------------------------GPU SETUP_______________-------------
wget https://bitbucket.org/cryptogone/arionum-gpu-miner/downloads/arionum-gpu-miner-v1.6.0-alpha-ubuntu16-cuda9.0.tar.gz
tar -xvzf arionum-gpu-miner-v1.6.0-alpha-ubuntu16-cuda9.0.tar.gz
rm run_OpenCL.sh
export NAME1=$(cat /root/.vast_containerlabel)
touch run_OpenCL.sh
echo '#! /bin/bash
# please change pool address, wallet address and worker ID to yours
# adjust -b & -t value as described in the README and FAQ
worker=$NAME1
pool="http://mine.arionumpool.com"
wallet="cis8i4z2HM7TRbw2jDnue4rh9Y8VDwBoMK2aDVPbcCiSwVYb9pEyoYNWxfJSraisASkkdb9MNfy6oRKS9BcHCWN"
threads="2"
batches="228"
# set this to false if you do not want miner to auto relaunch after crash
relaunch_miner_on_crash="true"
while :
do
    # -u means use all device, you can also use -d to specify list of devices (ex: -d 0,2,5)
    ./arionum-cuda-miner -u -b "$batches" -t "$threads" -p "$pool" -a "$wallet" -i "$worker"
    
    if [ "$relaunch_miner_on_crash" = "true" ]; then
        echo "miner crashed, relaunching in 5 seconds ..."
        sleep 5
    else
        break
    fi
done' > run_OpenCL.sh
chmod +x run_OpenCL.sh
apt-get -y install wget libcpprest libboost-all-dev ocl-icd-opencl-dev screen
screen -d -m ./run_OpenCL.sh


#----------shit for onstart.sh
touch /root/onstart.sh
echo '#!/bin/bash
screen -dmS miner /root/run_OpenCL.sh' > /root/onstart.sh
echo 'export NAME1=$(cat /root/.vast_containerlabel)' >> /root/onstart.sh
chmod +x /root/onstart.sh


#---------shit for /etc/rc.local------------
#touch /etc/rc.local
#echo 'screen -dmS miner /root/run_OpenCL.sh
#screen -dmS cpuminer /root/ariocppminer' | sudo cat - /etc/rc.local  > temp && sudo mv temp /etc/rc.local
#echo '#!/bin/sh -e' | sudo cat - /etc/rc.local  > temp && sudo mv temp /etc/rc.local
#chmod +x /etc/rc.local

#-------------Shit for CPU miner------
#apt-get -y install libssl-dev libcurl3
#wget https://bitbucket.org/cryptogone/ariocppminer/downloads/ariocppminer_v0.9.8_ubuntu16_server.tar.gz
#tar -xvzf ariocppminer_v0.9.8_ubuntu16_server.tar.gz
#touch config.cfg
#echo 'pool
#http://mine.arionumpool.com
#cis8i4z2HM7TRbw2jDnue4rh9Y8VDwBoMK2aDVPbcCiSwVYb9pEyoYNWxfJSraisASkkdb9MNfy6oRKS9BcHCWN
#0
#standard
#true
#$HOSTNAME'>>config.cfg
#screen -dmS cpuminer /root/ariocppminer
